package core

import (
	"testing"
)

func TestValidateIntent_ValidCreateIntent(t *testing.T) {
	intent := &ParsedIntent{
		Action: ActionCreate,
		Target: ResourceTarget{
			Kind:      "Deployment",
			Name:      "my-deployment",
			Namespace: "default",
		},
		Params:    map[string]interface{}{"replicas": 3},
		RiskLevel: RiskLow,
	}

	result := ValidateIntent(intent)
	if result != nil {
		t.Errorf("expected nil for valid intent, got %+v", result)
	}
}

func TestValidateIntent_ValidUpdateIntent(t *testing.T) {
	intent := &ParsedIntent{
		Action: ActionUpdate,
		Target: ResourceTarget{
			Kind:      "Deployment",
			Name:      "my-deployment",
			Namespace: "default",
		},
		Params:    map[string]interface{}{"replicas": 5},
		RiskLevel: RiskMedium,
		Reason:    "Scaling up for load",
	}

	result := ValidateIntent(intent)
	if result != nil {
		t.Errorf("expected nil for valid intent, got %+v", result)
	}
}

func TestValidateIntent_ValidDeleteIntent(t *testing.T) {
	intent := &ParsedIntent{
		Action: ActionDelete,
		Target: ResourceTarget{
			Kind:      "Deployment",
			Name:      "old-deployment",
			Namespace: "default",
		},
		RiskLevel: RiskHigh,
		Reason:    "Removing obsolete deployment",
	}

	result := ValidateIntent(intent)
	if result != nil {
		t.Errorf("expected nil for valid intent, got %+v", result)
	}
}

func TestValidateIntent_ValidInspectIntent(t *testing.T) {
	intent := &ParsedIntent{
		Action: ActionInspect,
		Target: ResourceTarget{
			Kind:      "Pod",
			Name:      "my-pod",
			Namespace: "default",
		},
		RiskLevel: RiskLow,
	}

	result := ValidateIntent(intent)
	if result != nil {
		t.Errorf("expected nil for valid intent, got %+v", result)
	}
}

func TestValidateIntent_InvalidAction(t *testing.T) {
	intent := &ParsedIntent{
		Action: Action("INVALID"),
		Target: ResourceTarget{
			Kind: "Deployment",
		},
	}

	result := ValidateIntent(intent)
	if result == nil {
		t.Fatal("expected ClarifyQuestion for invalid action, got nil")
	}
	if result.Field != "action" {
		t.Errorf("expected field 'action', got %s", result.Field)
	}
	if !result.Required {
		t.Error("expected Required to be true for invalid action")
	}
}

func TestValidateIntent_MissingKind(t *testing.T) {
	intent := &ParsedIntent{
		Action: ActionCreate,
		Target: ResourceTarget{
			Name:      "my-deployment",
			Namespace: "default",
		},
	}

	result := ValidateIntent(intent)
	if result == nil {
		t.Fatal("expected ClarifyQuestion for missing kind, got nil")
	}
	if result.Field != "target.kind" {
		t.Errorf("expected field 'target.kind', got %s", result.Field)
	}
	if !result.Required {
		t.Error("expected Required to be true for missing kind")
	}
}

func TestValidateIntent_MissingNameForUpdate(t *testing.T) {
	intent := &ParsedIntent{
		Action: ActionUpdate,
		Target: ResourceTarget{
			Kind:      "Deployment",
			Namespace: "default",
		},
	}

	result := ValidateIntent(intent)
	if result == nil {
		t.Fatal("expected ClarifyQuestion for missing name on UPDATE, got nil")
	}
	if result.Field != "target.name" {
		t.Errorf("expected field 'target.name', got %s", result.Field)
	}
}

func TestValidateIntent_MissingNameForDelete(t *testing.T) {
	intent := &ParsedIntent{
		Action: ActionDelete,
		Target: ResourceTarget{
			Kind:      "Deployment",
			Namespace: "default",
		},
	}

	result := ValidateIntent(intent)
	if result == nil {
		t.Fatal("expected ClarifyQuestion for missing name on DELETE, got nil")
	}
	if result.Field != "target.name" {
		t.Errorf("expected field 'target.name', got %s", result.Field)
	}
}

func TestValidateIntent_MissingNameForInspect(t *testing.T) {
	intent := &ParsedIntent{
		Action: ActionInspect,
		Target: ResourceTarget{
			Kind:      "Pod",
			Namespace: "default",
		},
	}

	result := ValidateIntent(intent)
	if result == nil {
		t.Fatal("expected ClarifyQuestion for missing name on INSPECT, got nil")
	}
	if result.Field != "target.name" {
		t.Errorf("expected field 'target.name', got %s", result.Field)
	}
}

func TestValidateIntent_NameOptionalForCreate(t *testing.T) {
	// For CREATE, name is generated by Kubernetes, so it's not required
	intent := &ParsedIntent{
		Action: ActionCreate,
		Target: ResourceTarget{
			Kind:      "Deployment",
			Namespace: "default",
		},
		RiskLevel: RiskLow,
	}

	result := ValidateIntent(intent)
	if result != nil {
		t.Errorf("expected nil for CREATE without name (name is optional), got %+v", result)
	}
}

func TestValidateIntent_MissingNamespaceForNamespacedKind(t *testing.T) {
	intent := &ParsedIntent{
		Action: ActionCreate,
		Target: ResourceTarget{
			Kind: "Deployment",
			Name: "my-deployment",
		},
	}

	result := ValidateIntent(intent)
	if result == nil {
		t.Fatal("expected ClarifyQuestion for missing namespace, got nil")
	}
	if result.Field != "target.namespace" {
		t.Errorf("expected field 'target.namespace', got %s", result.Field)
	}
}

func TestValidateIntent_NamespaceOptionalForClusterScopedKind(t *testing.T) {
	// Node is cluster-scoped, namespace is not required
	intent := &ParsedIntent{
		Action: ActionDelete,
		Target: ResourceTarget{
			Kind: "Node",
			Name: "worker-1",
		},
		RiskLevel: RiskHigh,
		Reason:    "Removing decommissioned node",
	}

	result := ValidateIntent(intent)
	if result != nil {
		t.Errorf("expected nil for cluster-scoped resource without namespace, got %+v", result)
	}
}

func TestValidateIntent_MissingReasonForHighRisk(t *testing.T) {
	intent := &ParsedIntent{
		Action: ActionDelete,
		Target: ResourceTarget{
			Kind:      "Deployment",
			Name:      "my-deployment",
			Namespace: "default",
		},
		RiskLevel: RiskHigh,
		// Reason is missing
	}

	result := ValidateIntent(intent)
	if result == nil {
		t.Fatal("expected ClarifyQuestion for missing reason on HIGH risk, got nil")
	}
	if result.Field != "reason" {
		t.Errorf("expected field 'reason', got %s", result.Field)
	}
}

func TestValidateIntent_MissingReasonForCriticalRisk(t *testing.T) {
	intent := &ParsedIntent{
		Action: ActionDelete,
		Target: ResourceTarget{
			Kind:      "Namespace",
			Name:      "critical-ns",
		},
		RiskLevel: RiskCritical,
		// Reason is missing
	}

	result := ValidateIntent(intent)
	if result == nil {
		t.Fatal("expected ClarifyQuestion for missing reason on CRITICAL risk, got nil")
	}
	if result.Field != "reason" {
		t.Errorf("expected field 'reason', got %s", result.Field)
	}
}

func TestValidateIntent_ReasonNotRequiredForLowRisk(t *testing.T) {
	intent := &ParsedIntent{
		Action: ActionInspect,
		Target: ResourceTarget{
			Kind:      "Pod",
			Name:      "my-pod",
			Namespace: "default",
		},
		RiskLevel: RiskLow,
		// Reason is not required for LOW risk
	}

	result := ValidateIntent(intent)
	if result != nil {
		t.Errorf("expected nil for LOW risk without reason, got %+v", result)
	}
}

func TestValidateIntent_MultipleIssuesReturnsFirst(t *testing.T) {
	// When multiple issues exist, we return the first one (in validation order)
	// Validation order: Action -> Target.Kind -> Target.Name -> Target.Namespace -> Reason
	intent := &ParsedIntent{
		Action: ActionUpdate,
		Target: ResourceTarget{
			// Missing Kind, Name, and Namespace
		},
		RiskLevel: RiskHigh,
	}

	result := ValidateIntent(intent)
	if result == nil {
		t.Fatal("expected ClarifyQuestion for invalid intent, got nil")
	}
	// First validation after Action is Target.Kind check (since ActionUpdate is valid)
	if result.Field != "target.kind" {
		t.Errorf("expected first error on 'target.kind' field, got %s", result.Field)
	}
}

func TestValidateIntent_HighRiskWithReasonSucceeds(t *testing.T) {
	intent := &ParsedIntent{
		Action: ActionDelete,
		Target: ResourceTarget{
			Kind:      "Deployment",
			Name:      "my-deployment",
			Namespace: "default",
		},
		RiskLevel: RiskHigh,
		Reason:    "Replacing with updated version",
	}

	result := ValidateIntent(intent)
	if result != nil {
		t.Errorf("expected nil for valid HIGH risk intent with reason, got %+v", result)
	}
}

func TestDefaultRiskLevel(t *testing.T) {
	tests := []struct {
		name     string
		intent   *ParsedIntent
		expected RiskLevel
	}{
		{
			name: "CREATE defaults to LOW",
			intent: &ParsedIntent{
				Action: ActionCreate,
				Target: ResourceTarget{Kind: "Deployment"},
			},
			expected: RiskLow,
		},
		{
			name: "UPDATE defaults to MEDIUM",
			intent: &ParsedIntent{
				Action: ActionUpdate,
				Target: ResourceTarget{Kind: "Deployment", Name: "test"},
			},
			expected: RiskMedium,
		},
		{
			name: "DELETE defaults to HIGH",
			intent: &ParsedIntent{
				Action: ActionDelete,
				Target: ResourceTarget{Kind: "Deployment", Name: "test"},
			},
			expected: RiskHigh,
		},
		{
			name: "INSPECT defaults to LOW",
			intent: &ParsedIntent{
				Action: ActionInspect,
				Target: ResourceTarget{Kind: "Pod", Name: "test"},
			},
			expected: RiskLow,
		},
		{
			name: "Unknown action defaults to LOW",
			intent: &ParsedIntent{
				Action: Action("UNKNOWN"),
				Target: ResourceTarget{Kind: "Deployment"},
			},
			expected: RiskLow,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			result := DefaultRiskLevel(tt.intent)
			if result != tt.expected {
				t.Errorf("expected %s, got %s", tt.expected, result)
			}
		})
	}
}

func TestIsNamespacedKind(t *testing.T) {
	tests := []struct {
		kind  string
		isNS  bool
	}{
		{"Deployment", true},
		{"Service", true},
		{"Pod", true},
		{"Node", false},
		{"Namespace", false},
		{"PersistentVolume", false},
		{"Unknown", false},
	}

	for _, tt := range tests {
		t.Run(tt.kind, func(t *testing.T) {
			result := IsNamespacedKind(tt.kind)
			if result != tt.isNS {
				t.Errorf("IsNamespacedKind(%s) = %v, want %v", tt.kind, result, tt.isNS)
			}
		})
	}
}